# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export PATH=$PATH:/usr/lib64/mpich/bin/
export LD_LIBRARY_PATH=$LDLIBRARY_PATH:/usr/lib64/mpich/lib/
